myapp/urls.py
from django.urls import path, include
from . import views

app_name = 'myapp'
urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  path('post_create', views.PostCreate.as_view(), name='post_create'),
  path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
  path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
  path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
  path('login', views.Login.as_view(), name='login'),
  path('logout', views.Logout.as_view(), name='logout'),
  path('signup', views.SignUp.as_view(), name='signup'),
  path('like/<int:post_id>', views.Like_add, name='like_add'),
  path('category_list', views.CategoryList.as_view(), name='category_list'),
  path('category_detail/<str:name_en>', views.CategoryDetail.as_view(), name='category_detail'),
  path('search', views.Search, name='search'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
  name = models.CharField('カテゴリ名', max_length=20)
  name_en = models.CharField('カテゴリ名英語', max_length=20)
  created_at = models.DateTimeField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)

  def post_count(self):
    n = Post.objects.filter(category = self).count()
    return n

  def __str__(self):
    return self.name

class Post(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
  title = models.CharField('タイトル', max_length=50)
  content = models.TextField('内容', max_length=990)
  category = models.ForeignKey('Category', on_delete=models.CASCADE)
  thumbnail = models.ImageField(upload_to='images/', blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)

  def like_count(self):
    n = Like.objects.filter(post = self).count()
    return n

  def __str__(self):
    return self.title

class Like(models.Model):
  post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.CASCADE)
  user = models.ForeignKey(User, verbose_name="likeしたユーザー", on_delete=models.CASCADE)

sitemanage/models.py
from django.db import models
from django.contrib.sites.models import Site


class SiteConfig(models.Model):
  site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
  meta_title = models.CharField('meta_title', max_length=100)
  meta_description = models.CharField('meta_description', max_length=300)
  meta_keywords = models.CharField('SEOキーワード', max_length=300)
  author = models.CharField('管理者', max_length=30)
  top_title = models.CharField('TOPページタイトル', max_length=100)
  top_subtitle = models.CharField('TOPページサブタイトル', max_length=200)

  def __str__(self):
    return self.meta_title

myapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('title', 'content', 'category', 'thumbnail')
  
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

class LoginForm(AuthenticationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

class SignUpForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    for field in self.fields.values():
      field.widget.attrs['class'] = 'form-control'

class SearchForm(forms.Form):
  freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)

myapp/views.py
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class OnlyMyPostMixin(UserPassesTestMixin):
  raise_exception = True
  def test_func(self):
    post = Post.objects.get(id = self.kwargs['pk'])
    return post.author == self.request.user

class Index(TemplateView):
  template_name = 'myapp/index.html'

  def get_context_data(self, *args, **kwargs):
    cotext = super().get_context_data(**kwargs)
    post_list = Post.objects.all().order_by('-created_at')
    context = { 'post_list': post_list, }
    return context

class PostCreate(LoginRequiredMixin, CreateView):
  model = Post
  form_class = PostForm
  success_url = reverse_lazy('myapp:index')

  def form_valid(self, form):
    form.instance.author_id = self.request.user.id
    return super(PostCreate, self).form_valid(form)

  def get_success_url(self):
    messages.success(self.request, '登録しました')
    return resolve_url('myapp:index')

class PostDetail(DetailView):
  model = Post

  def get_context_data(self, *args, **kwargs):
    detail_data = Post.objects.get(id = self.kwargs['pk'])
    category_posts = Post.objects.filter(category = detail_data.category).order_by('-created_at')[:5]
    params = { 'object': detail_data, 'category_posts': category_posts, }
    return params

class PostUpdate(OnlyMyPostMixin, UpdateView):
  model = Post
  form_class = PostForm

  def get_success_url(self):
    messages.info(self.request, '更新しました')
    return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])

class PostDelete(OnlyMyPostMixin, DeleteView):
  model = Post

  def get_success_url(self):
    messages.info(self.request, '削除しました')
    return resolve_url('myapp:index')

class Login(LoginView):
  form_class = LoginForm
  template_name = 'myapp/login.html'

class Logout(LogoutView):
  template_name = 'myapp/logout.html'

class SignUp(CreateView):
  form_class = SignUpForm
  template_name = 'myapp/signup.html'
  success_url = reverse_lazy('myapp:index')

  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    self.object = user
    messages.info(self.request, 'ユーザー登録をしました')
    return HttpResponseRedirect(self.get_success_url())

@login_required
def Like_add(request, post_id):
  post = Post.objects.get(id = post_id)
  is_liked = Like.objects.filter(user = request.user, post = post_id).count()
  if is_liked > 0:
    messages.info(request, 'すでにお気に入りにしています')
    return redirect('myapp:post_detail', post.id)
  like = Like()
  like.user = request.user
  like.post = post
  like.save()

  messages.success(request, 'お気に入りに追加しました')
  return redirect('myapp:post_detail', post.id)

class CategoryList(ListView):
  model = Category

class CategoryDetail(DetailView):
  model = Category
  slug_field = 'name_en'
  slug_url_kwarg = 'name_en'

  def get_context_data(self, *args, **kwargs):
    detail_data = Category.objects.get(name_en = self.kwargs['name_en'])
    category_posts = Post.objects.filter(category = detail_data.id).order_by('-created_at')
    params = { 'object': detail_data, 'category_posts': category_posts, }
    return params

def Search(request):
  if request.method == 'POST':
    searchform = SearchForm(request.POST)

    if searchform.is_valid():
      freeword = searchform.cleaned_data['freeword']
      search_list = Post.objects.filter(Q(title__icontains = freeword)|Q(content__icontains = freeword))

    params = { 'search_list': search_list, }
    return render(request, 'myapp/search.html', params)

def indexing(request):
    post_list = Post.objects.all().order_by('-created_at')
    paginator = Paginator(post_list, 4)
    page = request.GET.get('page')
    try:
    	page_obj = paginator.page(page)
    except PageNotAnInteger:
    	page_obj = paginator.page(1)
    except EmptyPage:
    	page_obj = paginator.page(paginator.num_pages)
    return render(request, 'myapp/index.html', {'page_obj': page_obj})

sitemanage/views.py
from django.shortcuts import render

# Create your views here.

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@yield('title')</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css" rel="stylesheet" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand me-2" href="/">
          <img src="https://3.bp.blogspot.com/-_kZIQRaeeHM/UAinA-j6ThI/AAAAAAAAF2U/oCFEmR7Ge9s/s1600/business_akusyu.png" height="22" alt="Logo"
            loading="lazy" style="margin-top: -1px;" />
          ナカマサガシ
        </a>

        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarButtonsExample"
          aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarButtonsExample">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:index' %}"><i class="fas fa-home fa-2x"></i></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="category"
                  role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                    カテゴリ
              </a>
              <ul class="dropdown-menu" aria-labelledby="category">
                {% for item in category_list %}
                <li>
                  <a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a>
                </li>
                {% endfor %}
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="{% url 'myapp:category_list' %}">カテゴリ一覧</a>
                </li>
              </ul>
            </li>
          </ul>

          <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
              <div class="nav-item">
                <a class="nav-link" href="{% url 'myapp:post_create' %}"><i class="far fa-plus-square fa-2x"></i></a>
              </div>
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="account"
                role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                  <i class="fas fa-user fa-2x"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="account">
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:logout' %}">ログアウト</a>
                  </li>
                </ul>
              </div>
              <form action="{% url 'myapp:search' %}" class="input-group w-auto" method="POST">
                {% csrf_token %}
                <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search", name="freeword">
                <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
              </form>
            {% else %}
              <a class="px-3 me-2" href="{% url 'myapp:login' %}">
                ログイン
              </a>
              <a  class="me-3" href="{% url 'myapp:signup' %}">
                新規登録
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <main class='container'>
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% block content %}
    {% endblock %}
    </main>
    <footer class="bg-light text-center text-white">
      <div class="container p-4 pb-0">
        <section class="mb-4">
          <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998;" href="#!" role="button"><i
              class="fab fa-facebook-f"></i></a>

          <!-- Twitter -->
          <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee;" href="#!" role="button"><i
              class="fab fa-twitter"></i></a>

          <!-- Google -->
          <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39;" href="#!" role="button"><i
              class="fab fa-google"></i></a>

          <!-- Instagram -->
          <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac;" href="#!" role="button"><i
              class="fab fa-instagram"></i></a>

          <!-- Linkedin -->
          <a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca;" href="#!" role="button"><i
              class="fab fa-linkedin-in"></i></a>
          <!-- Github -->
          <a class="btn btn-primary btn-floating m-1" style="background-color: #333333;" href="#!" role="button"><i
              class="fab fa-github"></i></a>
        </section>
      </div>

      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright: nakamasagashi.com
      </div>
    </footer>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.js"></script>
  </body>

</html>

myapp/templates/myapp/category_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<a href="javascript:void(0);" onclick="window.history.back();">＞ 戻る</a>
<h2 class="p-4 text-center">{{ object.name }}</h2>
<div class="row">
  {% for item in category_posts %}
  <div class="col-md-4">
    <div class="card">
      <div class="card-header"><strong>{{ item.author }}</strong></div>
      <img src="{{ item.thumbnail.url }}" class="card-img-top"
            alt="{{ item.title }}">
      <div class="card-body">
        <h4 class="card-title">{{ item.title }}</h4>
        <span class="badge badge-info">{{ item.category }}</span>
        <p class="card-text">{{ item.content }}</p>
        <a href="{% url 'myapp:post_detail' item.id %}">もっと読む</a>
        <p class="card-text">
          <small class="text-muted">{{ item.created_at }}</small>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

myapp/templates/myapp/category_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">カテゴリ一覧</h2>
<div class="row mb-8">
  <div class="col-md-6 offset-md-3 text-center">
    <div class="row">
    {% for item in category_list %}
      <div class="col-4">
        <a href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a><br>
        <small>[ {{ item.post_count }} ]</small>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">投稿一覧</h2>
<div class="row row-cols-1 row-cols-md-2 g-4">
  {% for item in post_list %}
  <div class="col">
    <div class="card">
      <div class="card-header align-items-center"><strong>{{ item.author }}</strong></div>
      <img src="{{ item.thumbnail.url }}" class="card-img-top"
        alt="{{ item.title }}">
        <a href="{% url 'myapp:post_detail' item.id %}"><div class="mask rgba-white-slight"></div></a>
      <div class="card-body">
        <h4 class="card-title">{{ item.title }}</h4>
        <span class="badge badge-info">{{ item.category }}</span>
        <p class="card-text">{{ item.content | truncatechars:50 }}</p>
        <a href="{% url 'myapp:post_detail' item.id %}">もっと読む</a>
        {% if item.like_count %}
          <i class="fas fa-heart fa-lg" style="color:rgb(255, 122, 155);"></i>{{ item.like_count }}
        {% endif %}
        <p class="card-text">
          <small class="text-muted">{{ item.created_at }}</small>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% include 'myapp/pagination.html' %}
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">ログイン</h2>
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="mb-4">
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
      </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary mb-4">ログイン</button>
    </form>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">ログアウト</h2>
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <p>ログアウトしました</p>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/pagination.html
<nav aria-label="Page navigation example m-4">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">前</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">前</a></li>
    {% endif %}

    {% for link_page in page_obj.paginator.page_range %}
      {% if link_page %}
        {% if link_page == page_obj.number %}
          <li class="page-item disabled"><a class="page-link" href="#">{{ link_page }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ link_page }}">{{ link_page }}</a></li>
        {% endif %}
      {% else %}
        <li class="page-item disabled"><a class="page-link text-muted" href="#">・・・</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">次</a></li>
    {% else %}
      <li class="page-item disabled"><div class="page-link" href="#">次</div></li>
    {% endif %}
  </ul>
</nav>

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">削除確認画面</h2>
<div class="row">
  <div class="col-md-6 offset-md-3 text-center mb-4">
    <div class="alert alert-danger" role="alert">
      <form method="post">
        {% csrf_token %}
        <p>本当に削除してよろしいですか？</p>
        <input type="submit" class="btn btn-danger" value="削除する">
      </form>
    </div>
    <h4>タイトル</h4>
    {{ object.title }}
    <h4>内容</h4>
    {{ object.content }}
  </div>
</div>
{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6 ms-md-auto">
    <div class="card m-3">
      <div class="card-header align-items-center"><strong>{{ object.author }}</strong></div>
      <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="{{ object.title }}"/>
      <div class="card-body">
        <h4 class="card-title">{{ object.title }}</h4>
        <p class="card-text">{{ object.content | linebreaksbr | urlize }}</p>
        <a href="{% url 'myapp:like_add' object.pk %}"><i class="fas fa-heart fa-2x" style="color:rgb(255, 122, 155);"></i></a>
        {% if object.author == request.user %}
        <a href="{% url 'myapp:post_update' object.id %}"><i class="fas fa-pencil-alt fa-2x" style="color:darkcyan;"></i></a>
        <a href="{% url 'myapp:post_delete' object.id %}"><i class="fas fa-trash-alt fa-2x" style="color:gray;"></i></a>
        {% endif %}
        <p class="card-text">
          <small class="text-muted">{{ object.created_at }}</small>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card text-center mt-4">
      <div class="card-body">
        <h4 class="card-title">{{ object.category }}</h4>
        <p class="card-text mt-4">このカテゴリの記事</p>
      </div>
      <ul class="list-group list-group-flush">
        {% for item in category_posts %}
        <li class="list-group-item"><a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">投稿内容</h2>
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-outline mb-4">
        {{ form.title }}
        <label class="form-label">タイトル</label>
      </div>
      <div class="mb-4">
        <label class="form-label">カテゴリー</label>
        {{ form.category }}
      </div>
      <div class="mb-4">
        <label class="form-label">画像</label>
        {{ form.thumbnail }}
      </div>
      <div class="form-outline mb-4">
        {{ form.content }}
        <label class="form-label">内容</label>
      </div>
      <button type="submit" class="btn btn-primary mb-4">保存</button>
    </form>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/search.html
{% extends 'myapp/base.html' %}

{% block content %}
<a href="javascript:void(0);" onclick="window.history.back();">＜ 戻る</a>
<h2 class="p-4 text-center">検索結果</h2>
<div class="row">
  {% for item in search_list %}
  <div class="col-md-4">
    <div class="card">
      <div class="card-header"><strong>{{ item.author }}</strong></div>
      <img src="{{ item.thumbnail.url }}" class="card-img-top"
            alt="{{ item.title }}">
      <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <span class="badge badge-info">{{ item.category }}</span>
        <p class="card-text">{{ item.content }}</p>
        <a href="{% url 'myapp:post_detail' item.id %}">もっと読む</a>
        <p class="card-text">
          <small class="text-muted">{{ item.created_at }}</small>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}

{% block content %}
<h2 class="p-5 text-center">新規登録</h2>
<div class="row">
  <div class="col-md-6 offset-md-3 text-center">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="mb-4">
        {{ field.label }}
        {{ field }}
        {{ field.errors }}
      </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary mb-4">新規登録</button>
    </form>
  </div>
</div>
{% endblock %}